language: ruby
rvm:
- 2.5.2
install:
- gem install bundler
- bundle install
script:
- bundle exec rspec --format doc
deploy:
  provider: heroku
  api_key:
    secure: gdiTZ6LiWLgBfop6/QY552Rq43AGORfWlepLJ7G5lk79DvAYHJpSji6XQYLbWnm4HMALmHnBrw+IyCPtfGqhAdiDEdxDRXQTVUeRxizi/cakjuL7R9wCmQZ9pY+jDMZojVnS1XrrcBlWBnLcR493QBnTrSdGDSMYWtgdeNdTQrBy4UZpj5A1giMpKIwQ0EOlIWLG9Pv83iQbCw6t7/3I3g0QRhal55oEIqGksG/KGnpB3ojTMdGj6pu4jUT/h6d9EuLD0n5rUPqRWjsK59+hQcZeh3IoCw26MJ7aKKU8nTiDcJJjtz+rmkOJekK/MvUVJVLOWguHKVfQRHSKt/h2PWCmiUMyA78UFhjHVrt9VhGXGkXCMNaKZGQiQ/W3vxYuCcJPxbLKcNVa44JZfIkcfe8gPukMWqWtS8BN5YqKgrK4o4DU4lgWxdmZS8ep0JFLY8puUaMhSL3u16Nd7yq2XUWVxzKOupIMxNF53twE6JlCv/6TMkVUYZBZzt2FBhQBm7bOI94A2BlKXdd2I1A4l6zmofMA2DoAd6x4rpWripNfo/aStLaMkW5jG8pj9ObBoy03NEaC8PHyW7ZrCnsk+S4/1/YeCsTOByQCdcDR3cXSziNmLLnzSCuS7n4uyM8DaVj6YWxVH97ad+hROTrUVKZdhbE7xjc38rNiSEgTyqg=
  app: ruby-tictactoe-api
  on:
    repo: AshleyByeUK/tictactoe-ruby-json-api
